<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/jquery-1.10.2.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/popper.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/bootstrap.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/owl.carousel.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/magnific-popup.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/waypoint.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/jquery.counterup.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/wow.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/jquery.fancybox.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/isotope.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/progresscircle.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/smooth-scrolling.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/particles.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/particlesRun.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/daterangepicker.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/tilt.jquery.min.js"></script>
<script src="<?= base_url() ?>assets/frontend/trivee/prizon/js/main.js"></script>